test:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=gouwradiotest'
      username: root
      password: GouwRadio!
      encoding: utf8
      attributes:
        default_table_collate: utf8_general_ci
        default_table_charset: utf8

all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=gouwradio'
      username: root
      password: GouwRadio!
      encoding: utf8
      attributes:
        default_table_collate: utf8_general_ci
        default_table_charset: utf8
      profiler: false
